[tools]
golang = "1.25.0"
golangci-lint = "2.12.2"

[tasks.build]
description = "Build the library"
run = "go build ./..."

[tasks.test]
description = "Run the tests"
run = "go test ./..."

[tasks.coverage]
description = "Run the tests with coverage"
run = "go test -cover ./..."

[tasks.lint]
description = "Run the linter"
run = "golangci-lint run ./..."

[tasks.format]
description = "Format the code"
run = "go fmt ./..."

[tasks.benchmark]
description = "Run the benchmarks"
run = "go test -run ^$ -bench '^BenchmarkParseUDP1$' -benchmem -benchtime=10s -memprofile=./ressources/mem.out -cpuprofile=./ressources/cpu.out -o ./ressources/benchmark.test ."

[tasks.profile-mem]
description = "Profile the memory usage"
run = "go tool pprof -alloc_space -list 'reliable.Parse' ./ressources/benchmark.test ./ressources/mem.out"

[tasks.profile-cpu]
description = "Profile the CPU usage"
run = "go tool pprof -list 'reliable.Parse' ./ressources/benchmark.test ./ressources/mem.out"

[tasks.profile]
description = "Profile the code"
usage = 'arg "<file>" default="./ressources/mem.prof" help="The profile file to profile"'
run = 'go tool pprof -http=:8085 "${usage_file?}"'

[tasks.validate]
description = "Validate the code"
run = "mise lint && mise format && mise test && mise build"
