[tools]
golang = "1.25.0"
golangci-lint = "2.12.2"

[tasks.build]
description = "Build the library"
run = "go build ./..."

[tasks.test]
description = "Run the tests"
run = "go test ./..."

[tasks.coverage]
description = "Run the tests with coverage"
run = "mkdir -p ./ressources && go test -cover ./... -coverprofile=ressources/coverage.out"

[tasks.coverage-html]
description = "Run the tests with coverage"
run = "go tool cover -html=ressources/coverage.out"

[tasks.lint]
description = "Run the linter"
run = "golangci-lint run ./..."

[tasks.format]
description = "Format the code"
run = "go fmt ./..."

[tasks.benchmark]
description = "Run the benchmarks"
run = "mkdir -p ./ressources && go test -run ^$ -bench '^BenchmarkParserOn343PacketsVersion18$' -benchmem -benchtime=10s -memprofile=./ressources/mem.out -cpuprofile=./ressources/cpu.out -o ./ressources/benchmark.test ."

[tasks.profile-mem]
description = "Profile the memory usage"
run = "mkdir -p ./ressources && go tool pprof -alloc_space -list 'reliable.Parse' ./ressources/benchmark.test ./ressources/mem.out"

[tasks.profile-cpu]
description = "Profile the CPU usage"
run = "mkdir -p ./ressources && go tool pprof -list 'reliable.Parse' ./ressources/benchmark.test ./ressources/cpu.out"

[tasks.validate]
description = "Validate the code"
run = "mise lint && mise format && mise test && mise build"
